data:
  root: /home/r22user1/fedavgmodels/sam_finetune/dataset/cityscapes
  bs: 1
  num_workers: 4
  n_pos: 10
  n_neg: 10

train:
  total_iters: 160000
  lr: 0.000001
  power: 1.
  show_interval: 20
  snapshot_interval: 5000
  valid_interval: 5000
  adaptor: decoder

eval:
  model: /home/r22user1/fedavgmodels/sam_finetune/exp/base/logs/Decoder_tuning.pth
  dataset: bdd100k